version: "3.9"
services:
  backend-project-service:
    image: bouwhulp-backend/project-service:latest
    ports:
      - "8120:8080"
      - "8121:8081"
  backend-user-service:
    image: bouwhulp-backend/user-service:latest
    ports:
      - "8110:8080"
      - "8111:8081"
  keycloak:
    image: jboss/keycloak:15.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak-bouwhulp-realm.json  -Dkeycloak.profile.feature.upload_scripts=enabled
    volumes:
      - type: bind
        source: ./keycloak-bouwhulp-realm.json
        target: /tmp/keycloak-bouwhulp-realm.json
    ports:
      - "8100:8080"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bouwhulp_db
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined